/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BilheteController;
import controller.PassageiroController;
import dao.DataSource;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bilhete;
import model.Passageiro;

/**
 *
 * @author ELITEBOOK
 */
public class TelaPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TelaCard
     */
    CardLayout cardLayout;
    List<Passageiro> listaPassageiros = PassageiroController.listaPassageiro();
    List<Bilhete> listaPrecos = BilheteController.listaPrecario();
    float precoD1 = listaPrecos.get(0).getPrecoD1();
    float precoD2 = listaPrecos.get(0).getPrecoD2();

    private Integer passId;

    public TelaPrincipalAdmin() {
        initComponents();
        Botoes(true, false, false, false, false);

        setLocationRelativeTo(null);
        addItems();
        readTable();
        totPassageirros();
        atualizarBtn.setEnabled(false);
        atualizarBtn.setVisible(false);
        cancelar.setEnabled(false);
        cancelar.setVisible(false);

        cardLayout = (CardLayout) (pnlCards.getLayout());
        //passar tudo para um metodo
        nomeIn.setDocument(new validarCaracteres(30, validarCaracteres.TipoEntrada.NOME));
        apelidoIn.setDocument(new validarCaracteres(30, validarCaracteres.TipoEntrada.NOME));
        contactoIn.setDocument(new validarCaracteres(9, validarCaracteres.TipoEntrada.CONTACTO));
        nomeUsuarioIn.setDocument(new validarCaracteres(30, validarCaracteres.TipoEntrada.USUARIO));
        palavraPasseIn.setDocument(new validarCaracteres(30, validarCaracteres.TipoEntrada.USUARIO));
        idadeIn.setDocument(new validarCaracteres(2, validarCaracteres.TipoEntrada.NUMEROINTEIRO));
        valorIn.setDocument(new validarCaracteres(10, validarCaracteres.TipoEntrada.NUMERODECIMAL));
        valorDepositoIn.setDocument(new validarCaracteres(10, validarCaracteres.TipoEntrada.NUMERODECIMAL));
        d1Valor.setDocument(new validarCaracteres(4, validarCaracteres.TipoEntrada.NUMERODECIMAL));
        d2Valor.setDocument(new validarCaracteres(4, validarCaracteres.TipoEntrada.NUMERODECIMAL));

        d1Valor.setText("" + precoD1);
        d2Valor.setText("" + precoD2);

        d1Valor.setEditable(false);
        d2Valor.setEditable(false);

        atualizarPrecoBtn1.setEnabled(false);
        atualizarPrecoBtn1.setVisible(false);
        cancelarBtn.setEnabled(false);
        cancelarBtn.setVisible(false);

    }

    public void addItems() {
        passageirosList.removeAllItems();
        for (Passageiro x : listaPassageiros) {
            passageirosList.addItem(x);
        }
    }

    public void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();

        modelo.setNumRows(0);

        for (Passageiro p : PassageiroController.listaPassageiro()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getApelido(),
                p.getContacto(),
                p.getNomeUsuario()
            });
        }

    }

    public void readTableByUsuario() {
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();

        modelo.setNumRows(0);

        List<Passageiro> lista = PassageiroController.listaPorNomeUsuario(pesquisaIn.getText());

        if (lista.size() == 0) {
            JOptionPane.showMessageDialog(this, "Usuario " + pesquisaIn.getText() + " nao encontrado");

            readTable();

            return;
        }

        for (Passageiro p : lista) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getApelido(),
                p.getContacto(),
                p.getNomeUsuario()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lista = new com.k33ptoo.components.KButton();
        sair = new com.k33ptoo.components.KButton();
        depositar = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();
        inicio = new com.k33ptoo.components.KButton();
        cadastrar = new com.k33ptoo.components.KButton();
        pnlCards = new javax.swing.JPanel();
        pnlCard4 = new javax.swing.JPanel();
        kGradientPanel4 = new com.k33ptoo.components.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTot = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        valorD1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        valorD2 = new javax.swing.JLabel();
        atualizarPrecoBtn = new com.k33ptoo.components.KButton();
        d2Valor = new javax.swing.JTextField();
        d1Valor = new javax.swing.JTextField();
        cancelarBtn = new com.k33ptoo.components.KButton();
        atualizarPrecoBtn1 = new com.k33ptoo.components.KButton();
        pnlCard1 = new javax.swing.JPanel();
        cadastro = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        apelido = new javax.swing.JLabel();
        nomeIn = new javax.swing.JTextField();
        apelidoIn = new javax.swing.JTextField();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        nomeUsuarioIn = new javax.swing.JTextField();
        salvar = new com.k33ptoo.components.KButton();
        atualizarBtn = new com.k33ptoo.components.KButton();
        cancelar = new com.k33ptoo.components.KButton();
        valor = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        contactoIn = new javax.swing.JTextField();
        idade = new javax.swing.JLabel();
        idadeIn = new javax.swing.JTextField();
        acesso = new javax.swing.JLabel();
        nomeUsuario = new javax.swing.JLabel();
        palavraPasse = new javax.swing.JLabel();
        valorIn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        palavraPasseIn = new javax.swing.JPasswordField();
        confpalavraPasseIn = new javax.swing.JPasswordField();
        pnlCard3 = new javax.swing.JPanel();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        atualizar = new com.k33ptoo.components.KButton();
        remover = new com.k33ptoo.components.KButton();
        pesquisaIn = new javax.swing.JTextField();
        Pesquisar = new com.k33ptoo.components.KButton();
        jLabel6 = new javax.swing.JLabel();
        listarTodos = new com.k33ptoo.components.KButton();
        pnlCard2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        passageirosList = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        valorDepositoIn = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_list_30px.png"))); // NOI18N
        lista.setText("Lista Passageiros");
        lista.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lista.setkBorderRadius(0);
        lista.setkEndColor(new java.awt.Color(255, 255, 255));
        lista.setkForeGround(new java.awt.Color(153, 153, 153));
        lista.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        lista.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        lista.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        lista.setkSelectedColor(new java.awt.Color(51, 51, 51));
        lista.setkStartColor(new java.awt.Color(255, 255, 255));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_exit_30px.png"))); // NOI18N
        sair.setText("Sair");
        sair.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sair.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        sair.setkBorderRadius(0);
        sair.setkEndColor(new java.awt.Color(255, 255, 255));
        sair.setkForeGround(new java.awt.Color(153, 153, 153));
        sair.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        sair.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sair.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        sair.setkStartColor(new java.awt.Color(255, 255, 255));
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        depositar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_money_30px.png"))); // NOI18N
        depositar.setText("Depositar");
        depositar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        depositar.setkBorderRadius(0);
        depositar.setkEndColor(new java.awt.Color(255, 255, 255));
        depositar.setkForeGround(new java.awt.Color(153, 153, 153));
        depositar.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        depositar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        depositar.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        depositar.setkSelectedColor(new java.awt.Color(51, 51, 51));
        depositar.setkStartColor(new java.awt.Color(255, 255, 255));
        depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ChapaCem");

        inicio.setForeground(new java.awt.Color(102, 102, 102));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bus_30px.png"))); // NOI18N
        inicio.setText("Inicio");
        inicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        inicio.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        inicio.setkBorderRadius(0);
        inicio.setkEndColor(new java.awt.Color(255, 255, 255));
        inicio.setkForeGround(new java.awt.Color(153, 153, 153));
        inicio.setkHoverColor(new java.awt.Color(153, 153, 153));
        inicio.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        inicio.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        inicio.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        inicio.setkSelectedColor(new java.awt.Color(51, 51, 51));
        inicio.setkStartColor(new java.awt.Color(255, 255, 255));
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        cadastrar.setForeground(new java.awt.Color(102, 102, 102));
        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_person_30px_4.png"))); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cadastrar.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        cadastrar.setkBorderRadius(0);
        cadastrar.setkEndColor(new java.awt.Color(255, 255, 255));
        cadastrar.setkForeGround(new java.awt.Color(153, 153, 153));
        cadastrar.setkHoverColor(new java.awt.Color(153, 153, 153));
        cadastrar.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        cadastrar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        cadastrar.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        cadastrar.setkSelectedColor(new java.awt.Color(51, 51, 51));
        cadastrar.setkStartColor(new java.awt.Color(255, 255, 255));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lista, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
            .addComponent(sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(depositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(depositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        pnlCards.setBackground(new java.awt.Color(0, 153, 153));
        pnlCards.setLayout(new java.awt.CardLayout());

        pnlCard4.setBackground(new java.awt.Color(102, 102, 255));
        pnlCard4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel4.setkBorderRadius(0);
        kGradientPanel4.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(153, 255, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Dados Gerais");

        jLabel7.setText("Nr Passageiros Registrados:");

        txtTot.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtTot.setText("0");

        jLabel10.setText("Precario dos bilhetes:");

        jLabel11.setText("Distancia D1: ");

        valorD1.setText("MTS");

        jLabel13.setText("Distancia D2: ");

        valorD2.setText("MTS");

        atualizarPrecoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_file_24px.png"))); // NOI18N
        atualizarPrecoBtn.setText("ATUALIZAR PRECOS");
        atualizarPrecoBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atualizarPrecoBtn.setkAllowGradient(false);
        atualizarPrecoBtn.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        atualizarPrecoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPrecoBtnActionPerformed(evt);
            }
        });

        d2Valor.setBackground(new java.awt.Color(255, 255, 255));
        d2Valor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        d2Valor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        d1Valor.setBackground(new java.awt.Color(255, 255, 255));
        d1Valor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        d1Valor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cancelarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_24px.png"))); // NOI18N
        cancelarBtn.setText("CANCELAR");
        cancelarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelarBtn.setkAllowGradient(false);
        cancelarBtn.setkBackGroundColor(new java.awt.Color(204, 0, 51));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        atualizarPrecoBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_file_24px.png"))); // NOI18N
        atualizarPrecoBtn1.setText("ATUALIZAR ");
        atualizarPrecoBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atualizarPrecoBtn1.setkAllowGradient(false);
        atualizarPrecoBtn1.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        atualizarPrecoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPrecoBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d1Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorD1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d2Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorD2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel8))
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarPrecoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                .addComponent(atualizarPrecoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorD1)
                    .addComponent(d1Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(d2Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorD2))
                .addGap(30, 30, 30)
                .addComponent(atualizarPrecoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarPrecoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pnlCard4.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 670));

        pnlCards.add(pnlCard4, "pnlCard4");

        pnlCard1.setBackground(new java.awt.Color(102, 102, 102));
        pnlCard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cadastro.setText("Cadastro de Passageiros");
        pnlCard1.add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 27, -1, -1));

        nome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nome.setText("Nome:");
        pnlCard1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 101, 108, -1));

        apelido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        apelido.setText("Apelido:");
        pnlCard1.add(apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 101, -1, -1));
        pnlCard1.add(nomeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 135, 237, 35));

        apelidoIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidoInActionPerformed(evt);
            }
        });
        pnlCard1.add(apelidoIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 135, 220, 35));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 255, 255));

        nomeUsuarioIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioInActionPerformed(evt);
            }
        });

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_24px.png"))); // NOI18N
        salvar.setText("SALVAR");
        salvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salvar.setkAllowGradient(false);
        salvar.setkBackGroundColor(new java.awt.Color(0, 153, 204));
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        atualizarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_file_24px.png"))); // NOI18N
        atualizarBtn.setText("ATUALIZAR");
        atualizarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atualizarBtn.setkAllowGradient(false);
        atualizarBtn.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtnActionPerformed(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_24px.png"))); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelar.setkAllowGradient(false);
        cancelar.setkBackGroundColor(new java.awt.Color(204, 0, 51));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        valor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        valor.setForeground(new java.awt.Color(255, 102, 102));
        valor.setText("Valor inicial do passageiro(MTS):");

        contacto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        contacto.setText("Contacto:");

        idade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        idade.setText("Idade:");

        acesso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acesso.setForeground(new java.awt.Color(255, 102, 102));
        acesso.setText("Dados de acesso a plataforma:");

        nomeUsuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nomeUsuario.setText("Nome do usuario:");

        palavraPasse.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        palavraPasse.setText("Palavra Passe:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Confirmar Palavra Passe:");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contacto)
                            .addComponent(contactoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acesso)
                            .addComponent(nomeUsuario)
                            .addComponent(nomeUsuarioIn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor)
                            .addComponent(valorIn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel12))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(confpalavraPasseIn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(palavraPasse)
                                        .addComponent(idade)
                                        .addComponent(idadeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(palavraPasseIn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacto)
                    .addComponent(idade))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(acesso)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeUsuario)
                    .addComponent(palavraPasse))
                .addGap(17, 17, 17)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeUsuarioIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palavraPasseIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(confpalavraPasseIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valor)
                .addGap(18, 18, 18)
                .addComponent(valorIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pnlCard1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 670));

        pnlCards.add(pnlCard1, "pnlCard1");

        pnlCard3.setBackground(new java.awt.Color(255, 51, 51));
        pnlCard3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel3.setkBorderRadius(0);
        kGradientPanel3.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 255, 255));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Apelido", "Contacto", "Nome  Usuario"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Lista de Passageiros");

        atualizar.setText("Atualizar");
        atualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atualizar.setkAllowGradient(false);
        atualizar.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        remover.setText("Remover");
        remover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remover.setkAllowGradient(false);
        remover.setkBackGroundColor(new java.awt.Color(204, 0, 51));
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Pesquisar pelo Nome do Usuario:");

        listarTodos.setText("Listar todos");
        listarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29))
                        .addGroup(kGradientPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(259, 259, 259)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(kGradientPanel3Layout.createSequentialGroup()
                            .addComponent(pesquisaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(listarTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(Pesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pnlCard3.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 670));

        pnlCards.add(pnlCard3, "pnlCard3");

        pnlCard2.setBackground(new java.awt.Color(102, 102, 255));
        pnlCard2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Escolher Passageiro:");
        pnlCard2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 106, 131, -1));

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Deposito para Passageiro");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Valor a depositar:");

        valorDepositoIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorDepositoInActionPerformed(evt);
            }
        });

        kButton1.setText("Depositar");
        kButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kButton1.setkAllowGradient(false);
        kButton1.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addGap(326, 326, 326)
                            .addComponent(jLabel2))
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(valorDepositoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passageirosList, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(91, 91, 91)
                .addComponent(passageirosList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorDepositoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        pnlCard2.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 670));

        pnlCards.add(pnlCard2, "pnlCard2");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Botoes(boolean i, boolean c, boolean d, boolean l, boolean s) {
        inicio.setSelected(i);
        cadastrar.setSelected(c);
        depositar.setSelected(d);
        lista.setSelected(l);
        sair.setSelected(s);

    }

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
        Botoes(false, false, false, true, false);
        cardLayout.show(pnlCards, "pnlCard3");

    }//GEN-LAST:event_listaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
//         Botoes(false, false, false, false, false);
        int opt = JOptionPane.showConfirmDialog(null, "Sair?", "Sair do sistema", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {

            this.dispose();
            new ChapaCemMain().setVisible(true);
        }
    }//GEN-LAST:event_sairActionPerformed

    private void depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarActionPerformed
        // TODO add your handling code here:
        Botoes(false, false, true, false, false);
        cardLayout.show(pnlCards, "pnlCard2");
    }//GEN-LAST:event_depositarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        Botoes(false, true, false, false, false);
        cardLayout.show(pnlCards, "pnlCard1");

    }//GEN-LAST:event_cadastrarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        //String nome, String apelido, int idade, String contacto, double saldoConta, String nomeUsuario, String palavraPasse

        if (nomeIn.getText().length() == 0 || apelidoIn.getText().length() == 0 || idadeIn.getText().length() == 0 || contactoIn.getText().length() == 0 || valorIn.getText().length() == 0 || nomeUsuarioIn.getText().length() == 0 || palavraPasseIn.getText().length() == 0 || confpalavraPasseIn.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos campos");

            return;
        }

        int idadeText = Integer.parseInt(idadeIn.getText());
        double saldoConta = Double.parseDouble(valorIn.getText());

        if (contactoIn.getText().length() < 9 || !contactoIn.getText().startsWith("" + 8)) {
            JOptionPane.showMessageDialog(this, "Por favor digite um numero de telefone valido: ");

            return;
        }

        if (saldoConta < 20) {
            JOptionPane.showMessageDialog(this, "Quantia minima e 20MTS");

            return;
        } else if (saldoConta > 5000) {
            JOptionPane.showMessageDialog(this, "Quantia maxima e 5000MTS");

            return;

        }

        if (idadeText < 15) {
            JOptionPane.showMessageDialog(this, "Idade minima 15 anos");

            return;
        }

        if (PassageiroController.verificarUsuatio(nomeUsuarioIn.getText())) {

            return;
        }

        if (!palavraPasseIn.getText().equals(confpalavraPasseIn.getText())) {
            JOptionPane.showMessageDialog(this, "Palavra passe incorreta");

            return;

        }

        if (PassageiroController.salvarPassageiro(nomeIn.getText(), apelidoIn.getText(), idadeText, contactoIn.getText(), saldoConta, nomeUsuarioIn.getText(), palavraPasseIn.getText())) {
            System.out.println("salvo com sucesso");
            apelidoIn.setText("");
            contactoIn.setText("");
            idadeIn.setText("");
            nomeIn.setText("");
            nomeUsuarioIn.setText("");
            palavraPasseIn.setText("");
            confpalavraPasseIn.setText("");
            valorIn.setText("");

            readTable();
            addItems();
            totPassageirros();

        }

    }//GEN-LAST:event_salvarActionPerformed

    private void apelidoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidoInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apelidoInActionPerformed

    private void valorDepositoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDepositoInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDepositoInActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:

        Passageiro p = (Passageiro) passageirosList.getSelectedItem();

        double quantia = Double.parseDouble(valorDepositoIn.getText());

        if (quantia < 20) {
            JOptionPane.showMessageDialog(this, "Quantia minima e 20MTS");

            return;
        } else if (quantia > 5000) {
            JOptionPane.showMessageDialog(this, "Quantia maxima e 5000MTS");

            return;

        }

        PassageiroController.depositar(p, quantia);

        valorDepositoIn.setText("");
    }//GEN-LAST:event_kButton1ActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:

        if (tabela.getSelectedRow() != -1) {
            int opt = JOptionPane.showConfirmDialog(null, "Tem a certeza que quer remover?", "remover", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {

                int linha = tabela.getSelectedRow();
                List<Passageiro> lista = PassageiroController.listaPassageiro();

                Passageiro p = lista.get(linha);

                System.out.println("id pass: " + p.getId());
                if (PassageiroController.removerPassageiro(p.getId())) {
                    readTable();
                    addItems();
                    totPassageirros();

                } else {
                    JOptionPane.showMessageDialog(this, "erro ao remover");
                }

                System.out.println("removido " + p);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione alguem");
        }
    }//GEN-LAST:event_removerActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:

        //if(tabela)
        if (tabela.getSelectedRow() != -1) {
            int linha = tabela.getSelectedRow();
            List<Passageiro> lista = PassageiroController.listaPassageiro();

            Passageiro p = lista.get(linha);

            apelidoIn.setText(p.getApelido());
            contactoIn.setText(p.getContacto());
            idadeIn.setText(Integer.toString(p.getIdade()));
            nomeIn.setText(p.getNome());
            nomeUsuarioIn.setText(p.getNomeUsuario());
            palavraPasseIn.setText(p.getPalavraPasse());
            valorIn.setText(Double.toString(p.getContaSaldo()));
            valorIn.setEnabled(false);
            palavraPasseIn.setEnabled(false);
            confpalavraPasseIn.setEnabled(false);

            setPassId(p.getId());

            salvar.setEnabled(false);
            salvar.setVisible(false);

            atualizarBtn.setEnabled(true);
            atualizarBtn.setVisible(true);

            cancelar.setEnabled(true);
            cancelar.setVisible(true);

            cardLayout.show(pnlCards, "pnlCard1");

            System.out.println(p);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione alguem");
        }

        /*
         CarroDao dao = new CarroDao(dataSource);

                List<Carro> lista = dao.readAll();

                int linha = tabela.getSelectedRow();

                Carro carro = lista.get(linha);
                
                System.out.println(carro);

                new TelaCadastro(this, carro).carrgarCampos();
         */
    }//GEN-LAST:event_atualizarActionPerformed

    private void nomeUsuarioInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioInActionPerformed

    private void atualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtnActionPerformed
        // TODO add your handling code here:
        if (nomeIn.getText().length() == 0 || apelidoIn.getText().length() == 0 || idadeIn.getText().length() == 0 || contactoIn.getText().length() == 0 || valorIn.getText().length() == 0 || nomeUsuarioIn.getText().length() == 0 || palavraPasseIn.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos campos");

            return;
        }
        System.out.println("id atual: " + passId);
        int idadeText = Integer.parseInt(idadeIn.getText());
        double saldoConta = Double.parseDouble(valorIn.getText());
        if (PassageiroController.atualizarPassageiro(nomeIn.getText(), apelidoIn.getText(), idadeText, contactoIn.getText(), saldoConta, nomeUsuarioIn.getText(), palavraPasseIn.getText(), passId)) {
            System.out.println("salvo com sucesso");
            apelidoIn.setText("");
            contactoIn.setText("");
            idadeIn.setText("");
            nomeIn.setText("");
            nomeUsuarioIn.setText("");
            palavraPasseIn.setText("");
            valorIn.setText("");

            readTable();

        }
        valorIn.setEnabled(true);
        palavraPasseIn.setEnabled(true);
        confpalavraPasseIn.setEnabled(true);

        atualizarBtn.setEnabled(false);
        atualizarBtn.setVisible(false);

        cancelar.setEnabled(false);
        cancelar.setVisible(false);

        salvar.setEnabled(true);
        salvar.setVisible(true);
    }//GEN-LAST:event_atualizarBtnActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        atualizarBtn.setEnabled(false);
        atualizarBtn.setVisible(false);

        cancelar.setEnabled(false);
        cancelar.setVisible(false);

        salvar.setEnabled(true);
        salvar.setVisible(true);

        apelidoIn.setText("");
        contactoIn.setText("");
        idadeIn.setText("");
        nomeIn.setText("");
        nomeUsuarioIn.setText("");
        palavraPasseIn.setText("");
        valorIn.setText("");
        valorIn.setEnabled(true);
        palavraPasseIn.setEnabled(true);
        confpalavraPasseIn.setEnabled(true);


    }//GEN-LAST:event_cancelarActionPerformed

    public void totPassageirros() {
        int totPass = PassageiroController.totPassageiro();

        txtTot.setText("" + totPass);
    }


    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        // TODO add your handling code here:

        if (pesquisaIn.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor digite algo");

            return;
        }

        readTableByUsuario();
    }//GEN-LAST:event_PesquisarActionPerformed

    private void listarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarTodosActionPerformed
        // TODO add your handling code here:
        readTable();
    }//GEN-LAST:event_listarTodosActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        Botoes(true, false, false, false, false);
        cardLayout.show(pnlCards, "pnlCard4");
    }//GEN-LAST:event_inicioActionPerformed

    private void atualizarPrecoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPrecoBtnActionPerformed
        // TODO add your handling code here:

        d1Valor.setEditable(true);
        d1Valor.requestFocus();
        d2Valor.setEditable(true);

        atualizarPrecoBtn1.setEnabled(true);
        atualizarPrecoBtn1.setVisible(true);
        cancelarBtn.setEnabled(true);
        cancelarBtn.setVisible(true);

        atualizarPrecoBtn.setEnabled(false);
        atualizarPrecoBtn.setVisible(false);


    }//GEN-LAST:event_atualizarPrecoBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:

        d1Valor.setEditable(false);
        d2Valor.setEditable(false);

        d1Valor.setText("" + precoD1);
        d2Valor.setText("" + precoD2);

        atualizarPrecoBtn1.setEnabled(false);
        atualizarPrecoBtn1.setVisible(false);
        cancelarBtn.setEnabled(false);
        cancelarBtn.setVisible(false);

        atualizarPrecoBtn.setEnabled(true);
        atualizarPrecoBtn.setVisible(true);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void atualizarPrecoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPrecoBtn1ActionPerformed
        // TODO add your handling code here:

        if (d1Valor.getText().length() == 0 || d2Valor.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos campos");

            return;

        }

        float d1 = Float.parseFloat(d1Valor.getText());
        float d2 = Float.parseFloat(d2Valor.getText());

        if (BilheteController.atualizarPrecario(d1, d2)) {
            d1Valor.setEditable(false);
            d2Valor.setEditable(false);

            atualizarPrecoBtn1.setEnabled(false);
            atualizarPrecoBtn1.setVisible(false);
            cancelarBtn.setEnabled(false);
            cancelarBtn.setVisible(false);

            atualizarPrecoBtn.setEnabled(true);
            atualizarPrecoBtn.setVisible(true);
        }
    }//GEN-LAST:event_atualizarPrecoBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Pesquisar;
    private javax.swing.JLabel acesso;
    private javax.swing.JLabel apelido;
    private javax.swing.JTextField apelidoIn;
    private com.k33ptoo.components.KButton atualizar;
    private com.k33ptoo.components.KButton atualizarBtn;
    private com.k33ptoo.components.KButton atualizarPrecoBtn;
    private com.k33ptoo.components.KButton atualizarPrecoBtn1;
    private com.k33ptoo.components.KButton cadastrar;
    private javax.swing.JLabel cadastro;
    private com.k33ptoo.components.KButton cancelar;
    private com.k33ptoo.components.KButton cancelarBtn;
    private javax.swing.JPasswordField confpalavraPasseIn;
    private javax.swing.JLabel contacto;
    private javax.swing.JTextField contactoIn;
    private javax.swing.JTextField d1Valor;
    private javax.swing.JTextField d2Valor;
    private com.k33ptoo.components.KButton depositar;
    private javax.swing.JLabel idade;
    private javax.swing.JTextField idadeIn;
    private com.k33ptoo.components.KButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField2;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel4;
    private com.k33ptoo.components.KButton lista;
    private com.k33ptoo.components.KButton listarTodos;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomeIn;
    private javax.swing.JLabel nomeUsuario;
    private javax.swing.JTextField nomeUsuarioIn;
    private javax.swing.JLabel palavraPasse;
    private javax.swing.JPasswordField palavraPasseIn;
    private javax.swing.JComboBox passageirosList;
    private javax.swing.JTextField pesquisaIn;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCard4;
    private javax.swing.JPanel pnlCards;
    private com.k33ptoo.components.KButton remover;
    private com.k33ptoo.components.KButton sair;
    private com.k33ptoo.components.KButton salvar;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel txtTot;
    private javax.swing.JLabel valor;
    private javax.swing.JLabel valorD1;
    private javax.swing.JLabel valorD2;
    private javax.swing.JTextField valorDepositoIn;
    private javax.swing.JTextField valorIn;
    // End of variables declaration//GEN-END:variables

    public Integer getPassId() {
        return passId;
    }

    public void setPassId(Integer passId) {
        this.passId = passId;
    }
}
