/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfWriter;

import controller.BilheteController;
import controller.PassageiroController;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import model.Bilhete;
import model.Paragens;
import model.Paragens2;
import model.Passageiro;
import model.Semi_ColectivoA;
import model.Semi_ColectivoB;

/**
 *
 * @author ELITEBOOK
 */
public class TelaPrincipalApp extends javax.swing.JFrame {

  
    //----------------------------
         Semi_ColectivoB chapa = new Semi_ColectivoB("mmc-33-02", 0);
         Semi_ColectivoB chapa2 = new Semi_ColectivoB("mmc-12-15", 1);
         
         Semi_ColectivoA chapa3 = new Semi_ColectivoA("mmc-83-12", 0);
         Semi_ColectivoA chapa4 = new Semi_ColectivoA("mmc-11-25", 1);
    
    //----------------
    List<Paragens2> lista1 = Arrays.asList(Paragens2.values());
    List<Paragens> lista = Arrays.asList(Paragens.values());
    
   
    Set<Thread> threadSet = Thread.getAllStackTraces().keySet();
    CardLayout cardLayout;
    private String nomePassagereiro;
    private double contaPassageiro;
    private Passageiro passageiro;
    float valor = 0.0f;
    List<Bilhete> listaPrecos = BilheteController.listaPrecario();
    float precoD1 = listaPrecos.get(0).getPrecoD1();
    float precoD2 = listaPrecos.get(0).getPrecoD2();
    ThreadsCells cells;

    /**
     * Creates new form TelaLoginApp
     */
    private TelaPrincipalApp() {

        initComponents();

        setLocationRelativeTo(null);
        rotas();
        transporte.setRenderer(new ThreadsCells());
        System.out.println(precoD1 + " - " + precoD2);
        cardLayout = (CardLayout) (views.getLayout());
        
    }

    public TelaPrincipalApp(Passageiro p) {
        this();

        nomeUsuarioLogado.setText("Bem vindo(a) " + p.getNome());
        setNomePassagereiro(p.getNome());
        setContaPassageiro(p.getContaSaldo());
        setPassageiro(p);

        setLocationRelativeTo(null);

    }

    public String getNomePassagereiro() {
        return nomePassagereiro;
    }

    public void setNomePassagereiro(String nomePassagereiro) {
        this.nomePassagereiro = nomePassagereiro;
    }

    public double getContaPassageiro() {
        return contaPassageiro;
    }

    public void setContaPassageiro(double contaPassageiro) {
        this.contaPassageiro = contaPassageiro;
    }

    public Passageiro getPassageiro() {
        return passageiro;
    }

    public void setPassageiro(Passageiro passageiro) {
        this.passageiro = passageiro;
    }

    private void rotas() {

        rotas.addItem("Alto-Mae-P.Combantentes");
        rotas.addItem("Central-Ronil");

        rotaBilhete.addItem("Alto-Mae-P.Combantentes");
        rotaBilhete.addItem("Central-Ronil");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        home = new com.k33ptoo.components.KButton();
        info = new com.k33ptoo.components.KButton();
        views = new javax.swing.JPanel();
        view1 = new javax.swing.JPanel();
        wifi1 = new javax.swing.JLabel();
        google1 = new javax.swing.JLabel();
        relogio1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        bateria1 = new javax.swing.JLabel();
        chapaLogo = new javax.swing.JLabel();
        rotasLbl = new javax.swing.JLabel();
        transporte = new javax.swing.JComboBox<>();
        paragens = new javax.swing.JLabel();
        pontoParagem = new javax.swing.JComboBox<>();
        ver = new com.k33ptoo.components.KButton();
        bilhete = new com.k33ptoo.components.KButton();
        rotas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        javaIcon3 = new javax.swing.JLabel();
        view2 = new javax.swing.JPanel();
        wifi = new javax.swing.JLabel();
        google = new javax.swing.JLabel();
        javaIcon = new javax.swing.JLabel();
        relogio = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        nomeUsuarioLogado = new javax.swing.JLabel();
        verSaldo = new com.k33ptoo.components.KButton();
        bateria = new javax.swing.JLabel();
        mudarPassword = new com.k33ptoo.components.KButton();
        terminarSessao2 = new com.k33ptoo.components.KButton();
        suporte = new com.k33ptoo.components.KButton();
        view4 = new javax.swing.JPanel();
        wifi2 = new javax.swing.JLabel();
        google2 = new javax.swing.JLabel();
        javaIcon1 = new javax.swing.JLabel();
        relogio2 = new javax.swing.JLabel();
        email2 = new javax.swing.JLabel();
        nomeUsuarioLogado1 = new javax.swing.JLabel();
        bateria2 = new javax.swing.JLabel();
        comprarBilhete = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        voltar = new com.k33ptoo.components.KButton();
        rotaBilhete = new javax.swing.JComboBox<>();
        destinoBilhete = new javax.swing.JComboBox<>();
        partidaBilhete = new javax.swing.JComboBox<>();
        destinolbl = new javax.swing.JLabel();
        view3 = new javax.swing.JPanel();
        wifi3 = new javax.swing.JLabel();
        google3 = new javax.swing.JLabel();
        javaIcon2 = new javax.swing.JLabel();
        relogio3 = new javax.swing.JLabel();
        email3 = new javax.swing.JLabel();
        nomeUsuarioLogado2 = new javax.swing.JLabel();
        bateria3 = new javax.swing.JLabel();
        mudar = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();
        txtconfirmpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtnovapass = new javax.swing.JPasswordField();
        txtatualpass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        voltar1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        home.setBackground(new java.awt.Color(51, 51, 51));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_home_30px.png"))); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        home.setIconTextGap(80);
        home.setkAllowGradient(false);
        home.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        home.setkBorderRadius(0);
        home.setMargin(new java.awt.Insets(2, 20, 2, 14));
        home.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_24px.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        info.setForeground(new java.awt.Color(204, 204, 204));
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_person_30px_4.png"))); // NOI18N
        info.setIconTextGap(80);
        info.setkAllowGradient(false);
        info.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        info.setkBorderRadius(0);
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        views.setBackground(new java.awt.Color(51, 51, 255));
        views.setLayout(new java.awt.CardLayout());

        view1.setBackground(new java.awt.Color(255, 255, 255));

        wifi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_wi-fi_connected_24px_2.png"))); // NOI18N

        google1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_google_16px.png"))); // NOI18N

        relogio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_clock_24px_1.png"))); // NOI18N

        email1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_gmail_24px_3.png"))); // NOI18N

        bateria1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_battery_level_30px.png"))); // NOI18N

        chapaLogo.setBackground(new java.awt.Color(51, 51, 255));
        chapaLogo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chapaLogo.setText("ChapaCem");

        rotasLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rotasLbl.setText("Rotas");

        transporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transporteActionPerformed(evt);
            }
        });

        paragens.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        paragens.setText("           PARAGENS");

        pontoParagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        }));

        ver.setText("Localizacao do Transporte");
        ver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ver.setkEndColor(new java.awt.Color(153, 153, 255));
        ver.setkHoverForeGround(new java.awt.Color(102, 102, 255));
        ver.setkHoverStartColor(new java.awt.Color(153, 153, 153));
        ver.setkStartColor(new java.awt.Color(153, 153, 153));
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        bilhete.setText("Comprar Bilhete");
        bilhete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bilhete.setkEndColor(new java.awt.Color(0, 102, 153));
        bilhete.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        bilhete.setkHoverForeGround(new java.awt.Color(153, 153, 255));
        bilhete.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        bilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilheteActionPerformed(evt);
            }
        });

        rotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Transportes disponiveis");

        javaIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_java_26px.png"))); // NOI18N

        javax.swing.GroupLayout view1Layout = new javax.swing.GroupLayout(view1);
        view1.setLayout(view1Layout);
        view1Layout.setHorizontalGroup(
            view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chapaLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(view1Layout.createSequentialGroup()
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(email1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javaIcon3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(google1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(relogio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wifi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bateria1))
                    .addGroup(view1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(view1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(paragens)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                .addGap(0, 118, Short.MAX_VALUE)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                        .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pontoParagem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                        .addComponent(rotasLbl)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        view1Layout.setVerticalGroup(
            view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bateria1)
                    .addComponent(wifi1)
                    .addComponent(relogio1)
                    .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(javaIcon3)
                        .addComponent(email1))
                    .addComponent(google1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chapaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(rotasLbl)
                .addGap(18, 18, 18)
                .addComponent(rotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(transporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(paragens)
                .addGap(18, 18, 18)
                .addComponent(pontoParagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(bilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        views.add(view1, "view1");

        view2.setBackground(new java.awt.Color(255, 255, 255));

        wifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_wi-fi_connected_24px_2.png"))); // NOI18N

        google.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_google_16px.png"))); // NOI18N

        javaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_java_26px.png"))); // NOI18N

        relogio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_clock_24px_1.png"))); // NOI18N

        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_gmail_24px_3.png"))); // NOI18N

        nomeUsuarioLogado.setBackground(new java.awt.Color(51, 102, 255));
        nomeUsuarioLogado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeUsuarioLogado.setForeground(new java.awt.Color(51, 51, 51));
        nomeUsuarioLogado.setText("Bem vindo(a) ");

        verSaldo.setForeground(new java.awt.Color(51, 102, 255));
        verSaldo.setText("Ver saldo");
        verSaldo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        verSaldo.setkAllowGradient(false);
        verSaldo.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        verSaldo.setkEndColor(new java.awt.Color(255, 255, 255));
        verSaldo.setkForeGround(new java.awt.Color(51, 102, 255));
        verSaldo.setkHoverForeGround(new java.awt.Color(51, 51, 255));
        verSaldo.setkStartColor(new java.awt.Color(102, 102, 102));
        verSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSaldoActionPerformed(evt);
            }
        });

        bateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_battery_level_30px.png"))); // NOI18N

        mudarPassword.setForeground(new java.awt.Color(51, 102, 255));
        mudarPassword.setText("Mudar palavraPasse");
        mudarPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mudarPassword.setkAllowGradient(false);
        mudarPassword.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        mudarPassword.setkForeGround(new java.awt.Color(51, 102, 255));
        mudarPassword.setkHoverForeGround(new java.awt.Color(51, 102, 255));
        mudarPassword.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        mudarPassword.setkSelectedColor(new java.awt.Color(51, 51, 255));
        mudarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarPasswordActionPerformed(evt);
            }
        });

        terminarSessao2.setForeground(new java.awt.Color(255, 0, 51));
        terminarSessao2.setText("Terminar Sessao");
        terminarSessao2.setkAllowGradient(false);
        terminarSessao2.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        terminarSessao2.setkForeGround(new java.awt.Color(255, 0, 51));
        terminarSessao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarSessao2ActionPerformed(evt);
            }
        });

        suporte.setForeground(new java.awt.Color(51, 102, 255));
        suporte.setText("Contacto e Suporte");
        suporte.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        suporte.setkAllowGradient(false);
        suporte.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        suporte.setkForeGround(new java.awt.Color(51, 102, 255));
        suporte.setkHoverForeGround(new java.awt.Color(51, 102, 255));
        suporte.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        suporte.setkSelectedColor(new java.awt.Color(51, 51, 255));
        suporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout view2Layout = new javax.swing.GroupLayout(view2);
        view2.setLayout(view2Layout);
        view2Layout.setHorizontalGroup(
            view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view2Layout.createSequentialGroup()
                .addGroup(view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javaIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(google)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(relogio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wifi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bateria))
                    .addGroup(view2Layout.createSequentialGroup()
                        .addGroup(view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(nomeUsuarioLogado))
                            .addGroup(view2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(verSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(view2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mudarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(view2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view2Layout.createSequentialGroup()
                    .addContainerGap(247, Short.MAX_VALUE)
                    .addComponent(terminarSessao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        view2Layout.setVerticalGroup(
            view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view2Layout.createSequentialGroup()
                .addGroup(view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bateria)
                    .addComponent(wifi)
                    .addComponent(google, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relogio)
                    .addGroup(view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(email)
                        .addComponent(javaIcon)))
                .addGap(72, 72, 72)
                .addComponent(nomeUsuarioLogado)
                .addGap(38, 38, 38)
                .addComponent(verSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(mudarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(suporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(view2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view2Layout.createSequentialGroup()
                    .addContainerGap(604, Short.MAX_VALUE)
                    .addComponent(terminarSessao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );

        views.add(view2, "view2");

        view4.setBackground(new java.awt.Color(255, 255, 255));

        wifi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_wi-fi_connected_24px_2.png"))); // NOI18N

        google2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_google_16px.png"))); // NOI18N

        javaIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_java_26px.png"))); // NOI18N

        relogio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_clock_24px_1.png"))); // NOI18N

        email2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_gmail_24px_3.png"))); // NOI18N

        nomeUsuarioLogado1.setBackground(new java.awt.Color(51, 102, 255));
        nomeUsuarioLogado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeUsuarioLogado1.setForeground(new java.awt.Color(51, 51, 51));
        nomeUsuarioLogado1.setText("Comprar bilhete");

        bateria2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_battery_level_30px.png"))); // NOI18N

        comprarBilhete.setText("Comprar");
        comprarBilhete.setkAllowGradient(false);
        comprarBilhete.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        comprarBilhete.setkHoverColor(new java.awt.Color(102, 102, 102));
        comprarBilhete.setkHoverForeGround(new java.awt.Color(153, 102, 255));
        comprarBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBilheteActionPerformed(evt);
            }
        });

        jLabel2.setText("Rota:");

        jLabel5.setText("Ponto de partida:");

        jLabel6.setText("Destino:");

        voltar.setText("Voltar");
        voltar.setkAllowGradient(false);
        voltar.setkBackGroundColor(new java.awt.Color(204, 0, 51));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        rotaBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotaBilheteActionPerformed(evt);
            }
        });

        destinoBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoBilheteActionPerformed(evt);
            }
        });

        partidaBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partidaBilheteActionPerformed(evt);
            }
        });

        destinolbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        destinolbl.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout view4Layout = new javax.swing.GroupLayout(view4);
        view4.setLayout(view4Layout);
        view4Layout.setHorizontalGroup(
            view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(email2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(javaIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(google2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(relogio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wifi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bateria2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view4Layout.createSequentialGroup()
                .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(nomeUsuarioLogado1)
                            .addComponent(jLabel5)
                            .addComponent(rotaBilhete, 0, 164, Short.MAX_VALUE)
                            .addComponent(partidaBilhete, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comprarBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(destinoBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        view4Layout.setVerticalGroup(
            view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view4Layout.createSequentialGroup()
                .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bateria2)
                    .addComponent(wifi2)
                    .addComponent(google2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relogio2)
                    .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(email2)
                        .addComponent(javaIcon1)))
                .addGap(72, 72, 72)
                .addComponent(nomeUsuarioLogado1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotaBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinoBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partidaBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addGroup(view4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprarBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        views.add(view4, "view4");

        view3.setBackground(new java.awt.Color(255, 255, 255));

        wifi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_wi-fi_connected_24px_2.png"))); // NOI18N

        google3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_google_16px.png"))); // NOI18N

        javaIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_java_26px.png"))); // NOI18N

        relogio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_clock_24px_1.png"))); // NOI18N

        email3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_gmail_24px_3.png"))); // NOI18N

        nomeUsuarioLogado2.setBackground(new java.awt.Color(51, 102, 255));
        nomeUsuarioLogado2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeUsuarioLogado2.setForeground(new java.awt.Color(51, 51, 51));
        nomeUsuarioLogado2.setText("Mudar Palavra Passe ");

        bateria3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_battery_level_30px.png"))); // NOI18N

        mudar.setText("Mudar");
        mudar.setkAllowGradient(false);
        mudar.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        mudar.setkHoverColor(new java.awt.Color(102, 102, 102));
        mudar.setkHoverForeGround(new java.awt.Color(153, 102, 255));
        mudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarActionPerformed(evt);
            }
        });

        jLabel3.setText("Confirmar palavra passe  nova:");

        txtconfirmpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtconfirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmpassActionPerformed(evt);
            }
        });

        jLabel7.setText("Palavra Passe atual:");

        txtnovapass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnovapass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnovapassActionPerformed(evt);
            }
        });

        txtatualpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtatualpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtatualpassActionPerformed(evt);
            }
        });

        jLabel8.setText("Palavra Passe nova:");

        voltar1.setText("Voltar");
        voltar1.setkAllowGradient(false);
        voltar1.setkBackGroundColor(new java.awt.Color(204, 0, 51));
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout view3Layout = new javax.swing.GroupLayout(view3);
        view3.setLayout(view3Layout);
        view3Layout.setHorizontalGroup(
            view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(email3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(javaIcon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(google3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(relogio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wifi3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bateria3)
                .addContainerGap())
            .addGroup(view3Layout.createSequentialGroup()
                .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(nomeUsuarioLogado2)
                            .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnovapass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtatualpass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(view3Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel7)
                    .addContainerGap(285, Short.MAX_VALUE)))
            .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(view3Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel8)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );
        view3Layout.setVerticalGroup(
            view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view3Layout.createSequentialGroup()
                .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bateria3)
                    .addComponent(wifi3)
                    .addComponent(google3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relogio3)
                    .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(email3)
                        .addComponent(javaIcon2)))
                .addGap(72, 72, 72)
                .addComponent(nomeUsuarioLogado2)
                .addGap(95, 95, 95)
                .addComponent(txtatualpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(txtnovapass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(view3Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jLabel7)
                    .addContainerGap(468, Short.MAX_VALUE)))
            .addGroup(view3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(view3Layout.createSequentialGroup()
                    .addGap(266, 266, 266)
                    .addComponent(jLabel8)
                    .addContainerGap(376, Short.MAX_VALUE)))
        );

        views.add(view3, "view3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(views, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(views, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(views, "view1");
    }//GEN-LAST:event_homeActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        cardLayout.show(views, "view2");
    }//GEN-LAST:event_infoActionPerformed

    private void transporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transporteActionPerformed
      
          
          
       if (String.valueOf(transporte.getSelectedItem()).contains("Alto")) {
            pontoParagem.removeAllItems();
            for (Paragens2 x : lista1) {
                pontoParagem.addItem(x.toString());
            }
        } else if (String.valueOf(transporte.getSelectedItem()).contains("Cent")) {
           
            pontoParagem.removeAllItems();
            for (Paragens x : lista) {
                pontoParagem.addItem(x.toString());
            }
        }
    }//GEN-LAST:event_transporteActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
     
        localizacaoPraca_ALtoMae();
        localizacaoCentral_Ronil();


    }//GEN-LAST:event_verActionPerformed

    private void bilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilheteActionPerformed
        // TODO add your handling code here:

        cardLayout.show(views, "view4");


    }//GEN-LAST:event_bilheteActionPerformed

    private void verSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSaldoActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, "O seu saldo actual e: " + passageiro.getContaSaldo());
    }//GEN-LAST:event_verSaldoActionPerformed

    private void terminarSessao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarSessao2ActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Terminar a sessao?", "Terminar sessao", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            this.dispose();

            new novaTelaLogin().setVisible(true);

        }
    }//GEN-LAST:event_terminarSessao2ActionPerformed

    private void rotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotasActionPerformed
        // TODO add your handling code here:

        if (rotas.getSelectedItem().equals("Alto-Mae-P.Combantentes")) {

            transporte.removeAllItems();
            for (Thread x : threadSet) {
                
               
               
                if ((x.getThreadGroup() == Thread.currentThread().getThreadGroup()) && (!x.getName().equals("DestroyJavaVM") && !x.getName().equals("AWT-EventQueue-0") && !x.getName().equals("mysql-cj-abandoned-connection-cleanup") && x.getName().substring(0, 4).equals("Alto"))) {
                    
                    transporte.addItem(x);
                    
                System.out.println(" teste: " + x.toString());
                    
                    System.out.println("thread atual: " + x);
                }
            }
        } else if (rotas.getSelectedItem().equals("Central-Ronil")) {

            transporte.removeAllItems();
            for (Thread x : threadSet) {

                if ((x.getThreadGroup() == Thread.currentThread().getThreadGroup()) && (!x.getName().equals("DestroyJavaVM") && !x.getName().equals("AWT-EventQueue-0") && !x.getName().equals("mysql-cj-abandoned-connection-cleanup") && x.getName().substring(0, 4).equals("Cent"))) {
                    
                    transporte.addItem(x);
                    System.out.println("thread atual: " + x.getName());
                }

            }
        }
    }//GEN-LAST:event_rotasActionPerformed

    private void suporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suporteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Contactos \n\n Telefone: 842883263 \n\n Email: suporte@chapacem.co.mz");
    }//GEN-LAST:event_suporteActionPerformed

    private void comprarBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBilheteActionPerformed
        // TODO add your handling code here:

        destinolbl.setText("");
        if (partidaBilhete.getSelectedItem().equals(destinoBilhete.getSelectedItem())) {
            // JOptionPane.showMessageDialog(this, "Destino invalido");
            destinolbl.setText("Destino invalido.");
            return;
        }

        bilheteCentral_Ronil();
        bilhetePraca_ALtoMae();

        Rectangle tamDoc = new Rectangle(400, 230);

        float columnWidth[] = {200f, 50f, 100f};

        Document document = new Document(tamDoc);

        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
       

        int opt = JOptionPane.showConfirmDialog(null, "Preco do bilhete: " + valor + "mts , continuar?", "Comprar bilhete", JOptionPane.YES_NO_OPTION);

        if (opt == 0) {
            if (passageiro.getContaSaldo() >= valor) {

                PassageiroController.comprarBilhete(passageiro, valor);
                BilheteController.salvarBilhete(passageiro);

                int nrBilhete = BilheteController.listaPassageiro();

                String nomeDocumento = "bilhete" + nrBilhete + ".pdf";

                try {
                    PdfWriter.getInstance(document, new FileOutputStream(nomeDocumento));

                    document.open();
                    document.add(new Paragraph("                         ChapaCem           "));

                    document.add(new Paragraph("Nome do Passageiro: " + nomePassagereiro + " " + passageiro.getApelido() + ";"));
                    document.add(new Paragraph("Rota: " + String.valueOf(rotaBilhete.getSelectedItem()) + ";"));
                    document.add(new Paragraph("Ponto de partida: " + String.valueOf(partidaBilhete.getSelectedItem()) + ";"));
                    document.add(new Paragraph("Destino: " + String.valueOf(destinoBilhete.getSelectedItem()) + ";"));
                    document.add(new Paragraph("Bilhete nr: " + nrBilhete));
                    document.add(new Paragraph("Total pago: " + valor + "mts"));
                    document.add(new Paragraph("Data: " + formatador.format(data) + ";"));

                    Desktop.getDesktop().open(new File(nomeDocumento));

                } catch (IOException | DocumentException ex) {
                    System.out.println("Erro: " + ex.getMessage());
                } finally {
                    document.close();

                }
            } else {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente");
            }

        }
    }//GEN-LAST:event_comprarBilheteActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        cardLayout.show(views, "view1");

    }//GEN-LAST:event_voltarActionPerformed

    private void mudarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarPasswordActionPerformed
        // TODO add your handling code here:
        cardLayout.show(views, "view3");

    }//GEN-LAST:event_mudarPasswordActionPerformed

    private void mudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarActionPerformed
        // TODO add your handling code here:
        String oldpass, newpass, confirmpass;

        oldpass = txtatualpass.getText();
        newpass = txtnovapass.getText();
        confirmpass = txtconfirmpass.getText();

        PassageiroController.mudarSenha(passageiro.getId(), oldpass, newpass, confirmpass);

        txtatualpass.setText("");
        txtnovapass.setText("");
        txtconfirmpass.setText("");

    }//GEN-LAST:event_mudarActionPerformed

    private void txtconfirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpassActionPerformed

    private void txtnovapassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnovapassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnovapassActionPerformed

    private void txtatualpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtatualpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtatualpassActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(views, "view2");
    }//GEN-LAST:event_voltar1ActionPerformed

    private void rotaBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotaBilheteActionPerformed
        // TODO add your handling code here:

        if (rotaBilhete.getSelectedItem().equals("Alto-Mae-P.Combantentes")) {
            partidaBilhete.removeAllItems();
            destinoBilhete.removeAllItems();
            for (Paragens2 x : lista1) {
                partidaBilhete.addItem(x.toString());
                destinoBilhete.addItem(x.toString());
            }
        } else if (rotaBilhete.getSelectedItem().equals("Central-Ronil")) {
            partidaBilhete.removeAllItems();
            destinoBilhete.removeAllItems();
            for (Paragens x : lista) {
                partidaBilhete.addItem(x.toString());
                destinoBilhete.addItem(x.toString());
            }
        }
    }//GEN-LAST:event_rotaBilheteActionPerformed

    private void destinoBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoBilheteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoBilheteActionPerformed

    private void partidaBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partidaBilheteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partidaBilheteActionPerformed

    private synchronized void localizacaoPraca_ALtoMae()  {
       
        
        
        int tempoEspera = 0;

          if (String.valueOf(transporte.getSelectedItem()).contains("Alto")) {
               Semi_ColectivoA A = (Semi_ColectivoA) transporte.getSelectedItem();
              // A.esperaMudar();
            if (pontoParagem.getSelectedItem().equals("ALTO_MAE") && A.getParagens().equals(Paragens2.PRACA)) {
                tempoEspera = 20;
            } else if (pontoParagem.getSelectedItem().equals("ALTO_MAE") && A.getParagens().equals(Paragens2.SHOPRITE)) {
                tempoEspera = 10;
            }

            if (pontoParagem.getSelectedItem().equals("SHOPRITE") && A.getParagens().equals(Paragens2.PRACA)) {
                tempoEspera = 10;
            } else if (pontoParagem.getSelectedItem().equals("SHOPRITE") && A.getParagens().equals(Paragens2.ALTO_MAE)) {
                tempoEspera = 10;
            }

            if (pontoParagem.getSelectedItem().equals("PRACA") && A.getParagens().equals(Paragens2.SHOPRITE)) {
                tempoEspera = 10;
            } else if (pontoParagem.getSelectedItem().equals("PRACA") && A.getParagens().equals(Paragens2.ALTO_MAE)) {
                tempoEspera = 20;
            }

         
         
             

            
            
              JOptionPane.showMessageDialog(this,"Transporte: " + A.getThreadName() + "\n\nLocalizacao atual: " + A.getParagens() + " || lotacao atual: " + A.getLotacaoAtual() + "/" + A.getLotacaoMax() + "\nTempo aproximado de espera: " + tempoEspera + " mins");
        }
    }

    private synchronized void localizacaoCentral_Ronil() {
        
        
        int tempoEspera = 0;

         if (String.valueOf(transporte.getSelectedItem()).contains("Cent")) {
              Semi_ColectivoB B = (Semi_ColectivoB) transporte.getSelectedItem();
              //B.esperaMudar();
            if (pontoParagem.getSelectedItem().equals("CENTRAL") && B.getParagens().equals(Paragens.RONIL)) {
                tempoEspera = 20;
            } else if (pontoParagem.getSelectedItem().equals("CENTRAL") && B.getParagens().equals(Paragens.PANDORA)) {
                tempoEspera = 10;
            }

            if (pontoParagem.getSelectedItem().equals("PANDORA") && B.getParagens().equals(Paragens.RONIL)) {
                tempoEspera = 10;
            } else if (pontoParagem.getSelectedItem().equals("PANDORA") && B.getParagens().equals(Paragens.CENTRAL)) {
                tempoEspera = 10;
            }

            if (pontoParagem.getSelectedItem().equals("RONIL") && B.getParagens().equals(Paragens.PANDORA)) {
                tempoEspera = 10;
            } else if (pontoParagem.getSelectedItem().equals("RONIL") && B.getParagens().equals(Paragens.CENTRAL)) {
                tempoEspera = 20;
            }

//           
             JOptionPane.showMessageDialog(this,"Transporte: " + B.getThreadName() + "\n\nLocalizacao atual: " + B.getParagens() + " || lotacao atual: " + B.getLotacaoAtual() + "/" + B.getLotacaoMax() + "\nTempo aproximado de espera: " + tempoEspera + " mins");
           
        }
    }

    private void bilheteCentral_Ronil() {

        if (rotaBilhete.getSelectedItem().equals("Central-Ronil")) {
            if (partidaBilhete.getSelectedItem().equals(Paragens.CENTRAL.toString()) && destinoBilhete.getSelectedItem().equals(Paragens.RONIL.toString())) {
                valor = precoD2;
            } else if (partidaBilhete.getSelectedItem().equals(Paragens.CENTRAL.toString()) && destinoBilhete.getSelectedItem().equals(Paragens.PANDORA.toString())) {
                valor = precoD1;
            }

            //pandora - ronil
            if (partidaBilhete.getSelectedItem().equals(Paragens.PANDORA.toString()) && destinoBilhete.getSelectedItem().equals(Paragens.RONIL.toString())) {
                valor = precoD1;
            } else if (partidaBilhete.getSelectedItem().equals(Paragens.PANDORA.toString()) && destinoBilhete.getSelectedItem().equals(Paragens.CENTRAL.toString())) {
                valor = precoD1;
            }
            //ronil pandora
            if (partidaBilhete.getSelectedItem().equals(Paragens.RONIL.toString()) && destinoBilhete.getSelectedItem().equals(Paragens.PANDORA.toString())) {
                valor = precoD1;
            } else if (partidaBilhete.getSelectedItem().equals(Paragens.RONIL.toString()) && destinoBilhete.getSelectedItem().equals(Paragens.CENTRAL.toString())) {
                valor = precoD2;
            }

        }
    }

    private void bilhetePraca_ALtoMae() {
        // int valor = 0;

        if (rotaBilhete.getSelectedItem().equals("Alto-Mae-P.Combantentes")) {
            if (partidaBilhete.getSelectedItem().equals(Paragens2.ALTO_MAE.toString()) && destinoBilhete.getSelectedItem().equals(Paragens2.PRACA.toString())) {
                valor = precoD2;
            } else if (partidaBilhete.getSelectedItem().equals(Paragens2.ALTO_MAE.toString()) && destinoBilhete.getSelectedItem().equals(Paragens2.SHOPRITE.toString())) {
                valor = precoD1;
            }

            //pandora - ronil
            if (partidaBilhete.getSelectedItem().equals(Paragens2.SHOPRITE.toString()) && destinoBilhete.getSelectedItem().equals(Paragens2.PRACA.toString())) {
                valor = precoD1;
            } else if (partidaBilhete.getSelectedItem().equals(Paragens2.SHOPRITE.toString()) && destinoBilhete.getSelectedItem().equals(Paragens2.ALTO_MAE.toString())) {
                valor = precoD1;
            }
            //ronil pandora
            if (partidaBilhete.getSelectedItem().equals(Paragens2.PRACA.toString()) && destinoBilhete.getSelectedItem().equals(Paragens2.SHOPRITE.toString())) {
                valor = precoD1;
            } else if (partidaBilhete.getSelectedItem().equals(Paragens2.PRACA.toString()) && destinoBilhete.getSelectedItem().equals(Paragens2.ALTO_MAE.toString())) {
                valor = precoD2;
            }

        }
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("erro " + ex.getMessage());
        } catch (InstantiationException ex) {
            System.out.println("erro " + ex.getMessage());
        } catch (IllegalAccessException ex) {
            System.out.println("erro " + ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println("erro " + ex.getMessage());
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipalApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bateria;
    private javax.swing.JLabel bateria1;
    private javax.swing.JLabel bateria2;
    private javax.swing.JLabel bateria3;
    private com.k33ptoo.components.KButton bilhete;
    private javax.swing.JLabel chapaLogo;
    private com.k33ptoo.components.KButton comprarBilhete;
    private javax.swing.JComboBox<String> destinoBilhete;
    private javax.swing.JLabel destinolbl;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email2;
    private javax.swing.JLabel email3;
    private javax.swing.JLabel google;
    private javax.swing.JLabel google1;
    private javax.swing.JLabel google2;
    private javax.swing.JLabel google3;
    private com.k33ptoo.components.KButton home;
    private com.k33ptoo.components.KButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel javaIcon;
    private javax.swing.JLabel javaIcon1;
    private javax.swing.JLabel javaIcon2;
    private javax.swing.JLabel javaIcon3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton mudar;
    private com.k33ptoo.components.KButton mudarPassword;
    public javax.swing.JLabel nomeUsuarioLogado;
    public javax.swing.JLabel nomeUsuarioLogado1;
    public javax.swing.JLabel nomeUsuarioLogado2;
    private javax.swing.JLabel paragens;
    private javax.swing.JComboBox<String> partidaBilhete;
    private javax.swing.JComboBox<String> pontoParagem;
    private javax.swing.JLabel relogio;
    private javax.swing.JLabel relogio1;
    private javax.swing.JLabel relogio2;
    private javax.swing.JLabel relogio3;
    private javax.swing.JComboBox<String> rotaBilhete;
    private javax.swing.JComboBox<String> rotas;
    private javax.swing.JLabel rotasLbl;
    private com.k33ptoo.components.KButton suporte;
    private com.k33ptoo.components.KButton terminarSessao2;
    private javax.swing.JComboBox<Thread> transporte;
    private javax.swing.JPasswordField txtatualpass;
    private javax.swing.JPasswordField txtconfirmpass;
    private javax.swing.JPasswordField txtnovapass;
    private com.k33ptoo.components.KButton ver;
    private com.k33ptoo.components.KButton verSaldo;
    private javax.swing.JPanel view1;
    private javax.swing.JPanel view2;
    private javax.swing.JPanel view3;
    private javax.swing.JPanel view4;
    private javax.swing.JPanel views;
    private com.k33ptoo.components.KButton voltar;
    private com.k33ptoo.components.KButton voltar1;
    private javax.swing.JLabel wifi;
    private javax.swing.JLabel wifi1;
    private javax.swing.JLabel wifi2;
    private javax.swing.JLabel wifi3;
    // End of variables declaration//GEN-END:variables
}
